pipeline {
  agent any
  stages {
    stage('Git Pull') {
      steps {
        git branch: "main", url: "https://github.com/BArturs/RTU_Devops_Course_2022/JenkinsPipeline"
      }
    }
    stage ('Test') {
      steps {
        echo 'testing in progress...'
        sh 'mvn clean test'
      }
    }
    stage ('Build') {
      steps {
        echo 'building in progress...'
        sh 'mvn clean compile assembly:single'
      }
    }
  }
}
